# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 07:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 7, 52, 23, 384581, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 7, 52, 23, 387195, tzinfo=utc)),
        ),
    ]
