# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 07:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20170209_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gps',
            old_name='speed',
            new_name='battery',
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 7, 56, 0, 661388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 7, 56, 0, 664257, tzinfo=utc)),
        ),
    ]
