# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 10:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0007_auto_20161110_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(default='+91', max_length=20)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2017, 2, 8, 10, 58, 13, 495916, tzinfo=utc))),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('profilePic', models.FileField(default='img/avatar5.png', upload_to='profile/')),
                ('verificationCode', models.CharField(default='zxsaqw', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
